### ISSUE TITLE
[DGA] Festival Shop Stock Errors

### ISSUE THREAD

**Issue by elizabethcd** [spacechase0/StardewValleyMods#178]
Issue: Errors and/or money is being taken from players when festival shops are opened
User log: https://smapi.io/log/29d927a8dfb04160ae167dd0d99fb874?renew=True
Sample Mod: Aster's Festival Kotatsu

This may be another one of the synch issues, not sure. 

Error in case log expires:
An error occurred in the base update loop: ArgumentException: An item with the same key has already been added. Key: DynamicGameAssets.Game.CustomBasicFurniturekey: 'DynamicGameAssets.Game.CustomBasicFurniture'
at System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[StardewValley.GameData.SpecialOrderData, StardewValley.GameData, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Add_Patch1(Dictionary`2 this, String key, SpecialOrderData value)
at DynamicGameAssets.Framework.PatchCommon.DoShop(String key, ShopMenu shop) in E:\source\_Stardew\Mods.spacechase0\DynamicGameAssets\Framework\PatchCommon.cs:line 23
at StardewValley.Event.checkAction_PatchedBy<spacechase0.DynamicGameAssets__spacechase0.SpaceCore>(Event this, Location tileLocation, Rectangle viewport, Farmer who)
at StardewValley.GameLocation.checkAction_PatchedBy<atravita.StopRugRemoval__DaLion.ImmersiveProfessions__greentodd.ActionSitting__PeacefulEnd.AlternativeTextures__PurrplingCat.QuestFramework>(GameLocation this, Location tileLocation, Rectangle viewport, Farmer who)
at StardewValley.Locations.Town.checkAction(Location tileLocation, Rectangle viewport, Farmer who)
at StardewValley.Game1.<>c__DisplayClass859_0.<tryToCheckAt>b__0()
at StardewValley.Game1.tryToCheckAt_PatchedBy<Platonymous.PyTK>(Vector2 grabTile, Farmer who)
at StardewValley.Game1.pressActionButton(KeyboardState currentKBState, MouseState currentMouseState, GamePadState currentPadState)
at StardewValley.Game1+c__DisplayClass913_0.<UpdateControlInput>b__0_PatchedBy<Shockah.DontStopMeNow>(<>c__DisplayClass913_0 this)
at StardewValley.Game1.UpdateControlInput(GameTime time)
at StardewValley.Game1._update(GameTime gameTime)
at StardewValley.Game1.Update(GameTime gameTime)
at StardewModdingAPI.Framework.SCore.OnPlayerInstanceUpdating(SGame instance, GameTime gameTime, Action runUpdate) in SMAPI\Framework\SCore.cs:line 1003

**Comment by spacechase0** [comment]
Actually, did you fix this one, or was that fix something else?
