### ISSUE TITLE
DGA BUG

### ISSUE THREAD

**Issue by martin66789** [spacechase0/StardewValleyMods#203]
I get this error:
https://smapi.io/log/df43c259c4d54968aae79ef64b676059?Levels=error%7Ealert%7Ecritical

**Comment by elizabethcd** [comment]
You have a _lot_ going on here, and it's not at all clear to me that this is a DGA bug. First of all, are you playing a multiplayer game? If so, you and your friends should try to all have the same mods, except for purely visual/recolors. Some of the other errors may also be related to this if so. 

Second of all, please remove all mods except DGA and content packs, and see if the error remains. If the error does not remain, then it's probably a mod conflict. You should then add back in mods until the error returns. Once the error returns, it's then most likely a conflict between the last mod you added and DGA. 

For future reference, the exact error:
This mod failed in the GameLoop.DayStarted event. Technical details: 
InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at Netcode.NetDictionary`5.KeysCollection.Enumerator.MoveNext() in C:\GitlabRunner\builds\Gq5qA5P4\1\ConcernedApe\stardewvalley\Farmer\Netcode\NetDictionary.cs:line 905
   at StardewValley.Network.OverlaidDictionary.KeysCollection.Enumerator.MoveNext()
   at SpaceShared.SpaceUtility._recursiveIterateLocation(GameLocation l, Func`2 action) in C:\Programming\StardewValley\ModSource\SpaceShared\SpaceUtility.cs:line 225
   at SpaceShared.SpaceUtility.iterateAllItems(Func`2 action) in C:\Programming\StardewValley\ModSource\SpaceShared\SpaceUtility.cs:line 71
   at DynamicGameAssets.PackData.ObjectPackData.OnDisabled() in C:\Programming\StardewValley\ModSource\DynamicGameAssets\PackData\ObjectPackData.cs:line 169
   at DynamicGameAssets.Mod.<OnDayStarted>g__DoEnableDisable|21_1(ContentIndexPackData parent, <>c__DisplayClass21_0& ) in C:\Programming\StardewValley\ModSource\DynamicGameAssets\Mod.cs:line 283
   at DynamicGameAssets.Mod.OnDayStarted(Object sender, DayStartedEventArgs e) in C:\Programming\StardewValley\ModSource\DynamicGameAssets\Mod.cs:line 296
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(Action`2 invoke, Func`2 match) in SMAPI\Framework\Events\ManagedEvent.cs:line 139

**Comment by martin66789** [comment]
I don't play in multiplayer mode.

I removed the DGA mods shown in the attached image one by one to see if there is a problem, but no. If I delete all the DGA modes shown in the picture then there is no error, but if I put it back to say the very first one then the error is already there.
![kép](https://user-images.githubusercontent.com/65812093/168320287-7ebf9085-2d6d-47d4-baee-75477e6cc013.png)
I can try to do it backwards by keeping the DGA mods and deleting the other mods, which will take a lot of time. The game takes about 5 minutes to load the menu and about 15 minutes to load the game state.

It's interesting that if I start the game only up to the menu there is no DGA error, only when I load my game state the DGA error occurs.
![kép](https://user-images.githubusercontent.com/65812093/168322069-c5b95de5-3893-4ea5-b017-cd34513fc365.png)

**Comment by elizabethcd** [comment]
To make it faster when removing all the other mods, remove them all at once.

**Comment by martin66789** [comment]
I deleted most of the mods, I get the following errors:
https://smapi.io/log/6879c1334286446aae0ae65c83541489

**Comment by elizabethcd** [comment]
So the DGA error now appears to be:
Error applying dynamic field: System.ArgumentException: No such key 'GiftTasteOverride' in dictionary 'ExtensionData'
   at DynamicGameAssets.PackData.DynamicFieldData.Apply(BasePackData obj_) in C:\Programming\StardewValley\ModSource\DynamicGameAssets\PackData\DynamicFieldData.cs:line 142
   at DynamicGameAssets.PackData.BasePackData.ApplyDynamicFields() in C:\Programming\StardewValley\ModSource\DynamicGameAssets\PackData\BasePackData.cs:line 53
   
Which is definitely a different error. I can't tell if this is an error in PPJA for DGA or an error in DGA, to be honest. I'm not really sure why you'd be getting one error with all your mods + DGA and a different one with just PPJA/DGA. I can poke a bit in the DGA source to see if I can spot anything obvious in that line, but I'm not going to be able to unravel the issues in the converted PPJA (there's a few, including the fact that PFM is completely incompatible with DGA items, and the MFM mail being misformatted, and the recipe shop entries being misformatted).

**Comment by martin66789** [comment]
The PPJA mod are here:
https://github.com/paradigmnomad/PPJA

**Comment by elizabethcd** [comment]
Okay, in terms of the latest error, my _guess_ is that there's a PPJA pack trying to use dynamic fields to change the field "GiftTasteOverride", for some reason, which does not exist, and therefore cannot be changed. I can't be sure, though. 

I'm aware of where to find the PPJA mods, I'm just not interested in fixing them as this would be a monumental task and they are not my mods.

**Comment by martin66789** [comment]
I got as far as [DGA] Starbrew Valley bringing up the No such key 'GiftTasteOverride' in dictionary 'ExtensionData' error.

Error applying dynamic field: System.ArgumentException: No such key 'GiftTasteOverride' in dictionary 'ExtensionData'
at DynamicGameAssets.PackData.DynamicFieldData.Apply(BasePackData obj_) in C:\Programming\StardewValley\ModSource\DynamicGameAssets\PackData\DynamicFieldData.cs:line 142
at DynamicGameAssets.PackData.BasePackData.ApplyDynamicFields() in C:\Programming\StardewValley\ModSource\DynamicGameAssets\PackData\BasePackData.cs:line 53

This is where to look for the error, deleting the 'Gift-Tastes.json' does not fix the error.



I see that the missing recipes that don't load have the following extra sorr in the 'Objects.json' file.
"EnableConditions":
    {
        "HasSeenEvent": "missingBundleComplete"
    },

**Comment by jodojodo** [comment]
Hello, I also have this issue, could you somehow resolve the problem or identify its root-cause?

**Comment by spacechase0** [comment]
DGA is no longer maintained.
