### ISSUE TITLE
Any ideas here?

### ISSUE THREAD

**Issue by TechieBlort** [spacechase0/StardewValleyMods#224]
I keep getting this error: 

```
[SpaceCore] Exception migrating legacy save data: System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at SpaceCore.Framework.LegacyDataMigrator.OnSaveLoaded() in C:\Programming\StardewValley\ModSource\SpaceCore\Framework\LegacyDataMigrator.cs:line 43
   at SpaceCore.SpaceCore.OnSaveLoaded(Object sender, SaveLoadedEventArgs e) in C:\Programming\StardewValley\ModSource\SpaceCore\SpaceCore.cs:line 197
[SpaceCore] This mod failed in the GameLoop.SaveLoaded event. Technical details:
ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at SpaceCore.Skills.OnSaveLoaded(Object sender, SaveLoadedEventArgs e) in C:\Programming\StardewValley\ModSource\SpaceCore\Skills.cs:line 271
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101
[SpaceCore] Doing skill menus
[Json Assets] This mod failed in the GameLoop.Saving event. Technical details:
ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at JsonAssets.Mod.OnSaving(Object sender, SavingEventArgs e) in C:\Programming\StardewValley\ModSource\JsonAssets\Mod.cs:line 1554
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101

```
regarding SpaceCore upon loading a completely brand new save.
Using these mods listed here:
![image](https://user-images.githubusercontent.com/29681046/172030649-de611088-8732-4c7f-aca9-2a8b14565744.png)
Any idea for what is causing my errors besides SpaceCore? It corupts the save past 1 play session. _Play session being closing the game and reopening it._

**Comment by spacechase0** [comment]
Could you get me a full log? https://smapi.io/log/

**Comment by TechieBlort** [comment]
https://smapi.io/log/05df9577a0944384be6fae97aab158ba this is the link to the full log.
Edit: Also updated all mods it says may resolve the issues to no avail still the same errors.

**Comment by spacechase0** [comment]
Your save is named oddly. For some reason it's missing the part before the underscore. Just add something (I think the usual is farm name), and then do the same for the file inside that directory with the same name.

> Context: loaded save '_314141734'
