### ISSUE TITLE
Moon Misadventures DGA Error

### ISSUE THREAD

**Issue by martin66789** [spacechase0/StardewValleyMods#278]
This mod failed in the GameLoop.DayStarted event. Technical details: 
InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at Netcode.NetDictionary`5.KeysCollection.Enumerator.MoveNext() in C:\GitlabRunner\builds\Gq5qA5P4\1\ConcernedApe\stardewvalley\Farmer\Netcode\NetDictionary.cs:line 905
   at StardewValley.Network.OverlaidDictionary.KeysCollection.Enumerator.MoveNext()
   at SpaceShared.SpaceUtility._recursiveIterateLocation(GameLocation l, Func`2 action) in C:\Programming\StardewValley\ModSource\SpaceShared\SpaceUtility.cs:line 225
   at SpaceShared.SpaceUtility.iterateAllItems(Func`2 action) in C:\Programming\StardewValley\ModSource\SpaceShared\SpaceUtility.cs:line 71
   at DynamicGameAssets.PackData.ObjectPackData.OnDisabled() in C:\Programming\StardewValley\ModSource\DynamicGameAssets\PackData\ObjectPackData.cs:line 169
   at DynamicGameAssets.Mod.<OnDayStarted>g__DoEnableDisable|25_1(ContentIndexPackData parent, <>c__DisplayClass25_0& ) in C:\Programming\StardewValley\ModSource\DynamicGameAssets\Mod.cs:line 306
   at DynamicGameAssets.Mod.OnDayStarted(Object sender, DayStartedEventArgs e) in C:\Programming\StardewValley\ModSource\DynamicGameAssets\Mod.cs:line 319
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101

**Comment by spacechase0** [comment]
Moon Misadventures and DGA are dead.
