### ISSUE TITLE
[Advanced Social Interaction/Skilltraining] Not work, Error

### ISSUE THREAD

**Issue by XiNaru** [spacechase0/StardewValleyMods#331]
Hey, i have both written mods, but....

`[Advanced Social Interactions] This mod failed in the Input.ButtonPressed event. Technical details:
NullReferenceException: Object reference not set to an instance of an object.
   at SkillTraining.Mod.GetTrainingMap() in C:\Programming\StardewValley\ModSource\SkillTraining\Mod.cs:line 129
   at SkillTraining.Mod.Asi_AdvancedInteractionStarted(Object sender, Action`2 e) in C:\Programming\StardewValley\ModSource\SkillTraining\Mod.cs:line 54
   at AdvancedSocialInteractions.Api.Invoke(NPC npc, Action`2 addCallback) in C:\Programming\StardewValley\ModSource\AdvancedSocialMenu\Mod.cs:line 25
   at AdvancedSocialInteractions.Mod.Input_ButtonPressed(Object sender, ButtonPressedEventArgs e) in C:\Programming\StardewValley\ModSource\AdvancedSocialMenu\Mod.cs:line 105
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101`

**Comment by spacechase0** [comment]
This mod hasn't been updated for 1.6 I think? Not completely dead like many others since I may update it eventually, but I'll close this for now since I'll probably revamp it to support custom skills and such if/when I do, which will completely change the place this error is occurring at.
