### ISSUE TITLE
Json Assets Code Error Report

### ISSUE THREAD

**Issue by qwweqeq** [spacechase0/StardewValleyMods#383]
When my Json Assets was implanted into the Mods folder, there was an issue that seems to be caused by an error in a certain line of code. Therefore, I am giving you feedback on this issue. The following is the code where the error occurred:

[Json Assets] Exception injecting cooking recipe for Bohe Lemon Soda: System.IO.InvalidDataException: No valid ingredients could be found, skipping this recipe.
   at JsonAssets.Data.ObjectRecipe.GetRecipeString(ObjectData parent) in C:\Programming\StardewValley\ModSource\JsonAssets\Data\ObjectRecipe.cs:line 48
   at JsonAssets.Framework.ContentInjector1.InjectDataCookingRecipes(IAssetData asset) in C:\Programming\StardewValley\ModSource\JsonAssets\Framework\ContentInjector1.cs:line 219

[Json Assets] Exception injecting cooking recipe for Bohe Popsicle: System.IO.InvalidDataException: No valid ingredients could be found, skipping this recipe.
   at JsonAssets.Data.ObjectRecipe.GetRecipeString(ObjectData parent) in C:\Programming\StardewValley\ModSource\JsonAssets\Data\ObjectRecipe.cs:line 48
   at JsonAssets.Framework.ContentInjector1.InjectDataCookingRecipes(IAssetData asset) in C:\Programming\StardewValley\ModSource\JsonAssets\Framework\ContentInjector1.cs:line 219

Do these errors affect the use of the module? I'm quite worried.

**Comment by sfortier32** [comment]
It seems more like an issue with whichever mod was trying to define the recipe. They probably used a custom object as an ingredient and didn't reference it properly or used an item code (for a SDV object) that doesn't exist. You can fix it yourself or just ignore those objects since those recipes are simply skipped and the rest of the pack's objects are added.

**Comment by spacechase0** [comment]
Yeah, that's an issue with the content pack. Besides problems with that specific recipe, everything should work fine.
