### ISSUE TITLE
JsonAssets Bug

### ISSUE THREAD

**Issue by mrtozkn** [spacechase0/StardewValleyMods#396]
[Json Assets] Failed to apply 'JsonAssets.Patches.GiantCropPatcher' patcher; some features may not work correctly. Technical details:
System.Exception: Parameter "tileLocation" not found in method virtual System.Void StardewValley.TerrainFeatures.GiantCrop::draw(Microsoft.Xna.Framework.Graphics.SpriteBatch spriteBatch)
   at HarmonyLib.MethodPatcher.EmitCallParameter(MethodInfo patch, Dictionary2 variables, LocalBuilder runOriginalVariable, Boolean allowFirsParamPassthrough, LocalBuilder& tmpObjectVar, List1 tmpBoxVars)
   at HarmonyLib.MethodPatcher.<>cDisplayClass36_0.<AddPrefixes>b0(MethodInfo fix)
   at HarmonyLib.MethodPatcher.AddPrefixes(Dictionary2 variables, LocalBuilder runOriginalVariable)
   at HarmonyLib.MethodPatcher.CreateReplacement(Dictionary2& finalInstructions)
   at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   at HarmonyLib.PatchProcessor.Patch()
   at JsonAssets.Patches.GiantCropPatcher.Apply(Harmony harmony, IMonitor monitor) in C:\Users\space\Programming\StardewValley\StardewValleyMods\JsonAssets\Patches\GiantCropPatcher.cs:line 25
   at Spacechase.Shared.Patching.HarmonyPatcher.Apply(Mod mod, IPatcher[] patchers) in
C:\Users\space\Programming\StardewValley\StardewValleyMods\SpaceSharedPatching\HarmonyPatcher.cs:line 21

**Comment by aravezskinteeth** [comment]
Same bug here!

**Comment by KrumpledPaper** [comment]
Same! Hopefully this gets fixed

**Comment by Iron237** [comment]
same bug too

**Comment by mrtozkn** [comment]
problem solved via next updates issue can be closed
