### ISSUE TITLE
[JsonAssets] Loading an old save triggers a `NullArgumentException: Value cannot be null`

### ISSUE THREAD

**Issue by bicobus** [spacechase0/StardewValleyMods#404]
I'm not quite sure how old this save is, but was running with stardew 1.5.

The effect is that stuff from [Producer Framework Mod](https://www.nexusmods.com/stardewvalley/mods/4970) appears with broken texture (or the existing mod I'm using is just broken).

```
[Json Assets]   Fucking_Machine_JA 1.0.0 by simezi21 - MOD 06
[Json Assets] This mod failed in the Specialized.LoadStageChanged event. Technical details: 
ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at JsonAssets.Mod.FixTerrainFeature(TerrainFeature feature) in C:\Users\space\Programming\StardewValley\StardewValleyMods\JsonAssets\Mod.cs:line 1880
   at SpaceShared.SpaceUtility._recursiveIterateLocation(GameLocation l, Func`2 action) in C:\Users\space\Programming\StardewValley\StardewValleyMods\SpaceShared\SpaceUtility.cs:line 47
   at SpaceShared.SpaceUtility.iterateAllTerrainFeatures(Func`2 action) in C:\Users\space\Programming\StardewValley\StardewValleyMods\SpaceShared\SpaceUtility.cs:line 21
   at JsonAssets.Mod.FixIdsEverywhere(Boolean reverse) in C:\Users\space\Programming\StardewValley\StardewValleyMods\JsonAssets\Mod.cs:line 1591
   at JsonAssets.Mod.OnLoadStageChanged(Object sender, LoadStageChangedEventArgs e) in C:\Users\space\Programming\StardewValley\StardewValleyMods\JsonAssets\Mod.cs:line 1196
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101
```

**Comment by bicobus** [comment]
Fixed with SV 1.6.3
