### ISSUE TITLE
[Bug][GMCM] Minor issue when pressing "Save" or "Save & Close" in Keybindings page

### ISSUE THREAD

**Issue by MithranArkanere** [spacechase0/StardewValleyMods#479]
```
[game] An error occurred in the base update loop: InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at GenericModConfigMenu.Framework.SpecificModConfigMenu.SaveConfig(Boolean playSound) in C:\Users\space\Programming\StardewValley\StardewValleyMods\GenericModConfigMenu\Framework\SpecificModConfigMenu.cs:line 704
   at GenericModConfigMenu.Framework.SpecificModConfigMenu.<>c__DisplayClass36_0.<AddDefaultLabels>b__5(Element _) in C:\Users\space\Programming\StardewValley\StardewValleyMods\GenericModConfigMenu\Framework\SpecificModConfigMenu.cs:line 643
   at SpaceShared.UI.Container.Update(Boolean isOffScreen) in C:\Users\space\Programming\StardewValley\StardewValleyMods\SpaceShared\UI\Container.cs:line 75
   at SpaceShared.UI.RootElement.Update(Boolean isOffScreen) in C:\Users\space\Programming\StardewValley\StardewValleyMods\SpaceShared\UI\RootElement.cs:line 29
   at GenericModConfigMenu.Framework.SpecificModConfigMenu.update(GameTime time) in C:\Users\space\Programming\StardewValley\StardewValleyMods\GenericModConfigMenu\Framework\SpecificModConfigMenu.cs:line 489
   at StardewValley.Game1.updateActiveMenu(GameTime gameTime) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\Game1.cs:line 4795
   at StardewValley.Game1._update(GameTime gameTime) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\Game1.cs:line 4010
   at StardewValley.Game1.Update(GameTime gameTime) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\Game1.cs:line 3185
   at StardewModdingAPI.Framework.SCore.OnPlayerInstanceUpdating(SGame instance, GameTime gameTime, Action runUpdate) in SMAPI\Framework\SCore.cs:line 1084
[game] WARNING: Mismatched UI Mode Push/Pop counts. Correcting.
```

https://smapi.io/log/b6b2d80ea8824038aca9b5ffa2096577

This error appears twice in a row when pressing "Save" or "Save & Close" at the Keybindings page.  
It does not prevent saving the configuration or any other issue I could notice, other than the page not closing when choosing "Save & Close".

**Comment by spacechase0** [comment]
Hopefully fixed in upcoming 1.13.2. (Posting to Nexus momentarily)
